name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install LuaLaTeX
      run: |
        sudo apt install -qq -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-latex-recommended

    - name: Build *.tex files to PDFs
      run: |
        cd vtrmc/tex
        for year in [1-9]* ; do
          # The begin/end markers enable having collapsible sections in the
          # output, which improves readability.
          #
          # See the docs for details:
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

          echo "::group::VTRMC ${year} problems"
          make -C "${year}" problems
          echo "::endgroup::"

          echo "::group::VTRMC ${year} solutions"
          make -C "${year}" solutions
          echo "::endgroup::"
        done
      env:
        VERBOSE: 1

    - name: Install Typst
      run: |
        # Download Typst, decompress it, and add its directory to $PATH.
        curl -sOL "https://github.com/typst/typst/releases/download/${TYPST_VERSION}/${TYPST_BUILD}.tar.xz"
        tar xf "${TYPST_BUILD}.tar.xz"
        echo "${PWD}/${TYPST_BUILD}" >> "${GITHUB_PATH}"
      env:
        TYPST_VERSION: v0.6.0
        TYPST_BUILD: typst-x86_64-unknown-linux-musl

    - name: Build *.typ files to PDFs
      run: |
        cd vtrmc/typ
        for year in [1-9]* ; do
          echo "::group::VTRMC ${year} problems"
          make -C "${year}" problems
          echo "::endgroup::"

          echo "::group::VTRMC ${year} solutions"
          make -C "${year}" solutions
          echo "::endgroup::"
        done
      env:
        VERBOSE: 1
