name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install LuaLaTeX
      run: |
        sudo apt install -qq -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-latex-recommended

    - name: Build contest PDFs
      run: |
        cd vtrmc
        for year in [1-9]* ; do
          # The begin/end markers enable having collapsible sections in the
          # output, which improves readability.
          #
          # See the docs for details:
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

          echo "::group::VTRMC ${year} problems"
          make -C "${year}" problems
          echo "::endgroup::"

          echo "::group::VTRMC ${year} solutions"
          make -C "${year}" solutions
          echo "::endgroup::"
        done
